language: php

php:
  - 7.0

sudo: false

before_install:
  - cp .env.travis .env
  - mysql -e 'create database testing;'
  - composer self-update

install:
  - composer install --prefer-dist --no-interaction --prefer-stable
  - php artisan migrate

script: vendor/bin/phpunit
