language: php

php:
  - 7.0

sudo: false

before_install:
  - cp .env.travis .env
  - mysql -e 'create database testing;'
  - composer self-update

install:
  - composer install --no-interaction
  - php artisan migrate
  - npm install
  - node_modules/.bin/gulp

script: vendor/bin/phpunit
